POST http://localhost:3000/api/topics HTTP/1.1
Content-Type: application/json

{
    "title":"topic1",
    "description":"topic1"
}
###
GET http://localhost:3000/api/topics HTTP/1.1
###
GET http://localhost:3000/api/topics?id=6583517842a19359dd54f97a HTTP/1.1
###
DELETE  http://localhost:3000/api/topics?id=658350a703865c28363d6cd8 HTTP/1.1
###
PUT http://localhost:3000/api/topics?id=6583517842a19359dd54f97a HTTP/1.1
Content-Type: application/json

{
    "newTitle":"thisfff a new topic",
    "newDescription":"this is a new topic"
}